export const REQUEST_USER_DETAILS = 'user/REQUEST_USER_DETAILS';
export const RECEIVE_USER_DETAILS = 'user/RECEIVE_USER_DETAILS'
export const REQUEST_EDIT_DETAILS = 'user/REQUEST_EDIT_DETAILS';
export const REQUEST_DELETE_DETAILS = 'user/REQUEST_DELETE_DETAILS';
export const REQUEST_DETAIL_FAILURE = 'user/REQUEST_DETAIL_FAILURE';
